export const STORE = {
  name: "Brother's Fashion Zone",
  owner: 'Ashok Patel',
  email: "Brothers'sfashion@gmail.com",
  phone: '+91 81410 01555',
  phoneRaw: '918141001555',
  upiId: 'ashokpatela119-1@oksbi',
  upiName: 'Ashok Ashokpatel',
  qrImage: '/images/upi-qr.png',
  whatsappBase: 'https://wa.me/918141001555',
  instagram: 'https://instagram.com/brothersfashionzone',
  adminEmail: 'admin@brothersfashion.com',
  hours: 'Mon–Sat: 10:00 AM – 7:00 PM',
  sunday: 'Sunday: Closed',
  freeDelivery: 599,
  orderPrefix: 'BFZ',
  year: 2026,
} as const;